DROP TABLE IF EXISTS equips;
DROP TABLE IF EXISTS rituals;
DROP TABLE IF EXISTS fusions;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS stars;

CREATE TABLE cards (
	Id INTEGER PRIMARY KEY NOT NULL,
	Name INTEGER NOT NULL,
	Description TEXT NOT NULL,
	GuardianStarA INTEGER NOT NULL,
	GuardianStarB INTEGER NOT NULL,
	Level INTEGER NOT NULL,
	Type INTEGER NOT NULL,
	Attack INTEGER NOT NULL,
	Defense INTEGER NOT NULL,
	Stars INTEGER NOT NULL,
	CardCode INTEGER NOT NULL,
	Attribute INTEGER NOT NULL
);


CREATE TABLE equips (
	Equip_id INTEGER NOT NULL,
	Equipped_id INTEGER NOT NULL
);


CREATE TABLE rituals (
	Ritual_id INTEGER NOT NULL,
	Card1 INTEGER NOT NULL,
	Card2 INTEGER NOT NULL,
	Card3 INTEGER NOT NULL,
	Result INTEGER NOT NULL
);


CREATE TABLE fusions (
	Card1 INTEGER NOT NULL,
	Card2 INTEGER NOT NULL,
	Result INTEGER NOT NULL
);


CREATE TABLE types (
	Id INTEGER PRIMARY KEY NOT NULL,
	Type TEXT NOT NULL
);


CREATE TABLE stars (
	Id INTEGER PRIMARY KEY NOT NULL,
	Star TEXT NOT NULL
);
